spring:
  graphql:
    graphiql:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  datasource:
    hikari:
      pool-name: h2-pool
logging:
  level:
    sql: debug
    web: debug